#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.4.0}
EDITION=${3:-community}

curl -s https://raw.githubusercontent.com/mandrills/docker-magento/master/lib/template | bash
bin/download $VERSION $EDITION

echo "请输入系统密码才能将条目添加到/etc/hosts......"
echo "127.0.0.1 ::1 $DOMAIN" | sudo tee -a /etc/hosts

bin/setup $DOMAIN
